l=float(input('Enter Length     :'))
b=float(input('Enter Breadth    : '))
print('The value of Length      :',l)
print('The value of Breadth     :',b)
print('Area of Rectangle        :',l*b)
print('Perimeter of Rectangle   :',2*(l+b))
