num1=int(input('Enter Number-1: '))
num2=int(input('Enter Number-2: '))
print("First Number :",num1)
print("Second Number:",num2)
print('Addition of    :',num1,num2,num1+num2)
print('Substraction   :',num1,num2,num1-num2)
print('Product of     :',num1,num2,num1*num2)
print('Quotient       :',num1,num2,num1/num2)
print('Remainder      :',num1,num2,num1%num2)
print('Floor Division :',num1,num2,num1//num2)