num1=int(input('Enter number-1 :'))
num2=float(input('Enter number-2 :'))
num3=float(input('Enter number- 3'))
print('Number-1',num1,type(num1))
print('Number-2',num2,type(num2))
print('Number-3',num3,type(num3))