s=input('Enter any String   :')
print('Capatilize    :',s.capitalize())
print('Case fold     :',s.casefold())
print('String Lower  :',s.islower())
print('String Upper  :',s.isupper())
# print('String SPlit  :',s.split('%'))
print('String Center :',s.center(10))
print('String Alnum  :',s.isalnum())
print('String Alpha  :',s.isalpha())
print('String Ascii  :',s.isascii())
print('String Decimal',s.isdecimal())
print('String Digit  :',s.isdigit())
print('String Title  :',s.title())
print('String Print  :',s.isprintable())
print('String Swap Case:',s.swapcase())
print('String Strip    :',s.strip())